---
ansible_python_interpreter: /usr/local/bin/python3.11

wan_interface: vtnet0
trunk_interface: vtnet1

Lan_vlan: 10
admin_vlan: 30

lan_ip: 192.168.10.1
admin_ip: 192.168.30.1

lan_vm_ip: 192.168.10.101
admin_vm_ip: 192.168.30.101

# NAT ports WAN → VMs internes
lan_vm_nat_port: "2226"
admin_vm_nat_port: "2225"

# IPs externes autorisees
epitech_network_ip: "163.5.3.84"
jaures_network_ip: "94.238.238.44"

# VPN Site-a-Site
vpn_tunnel_network: "10.0.0.0/30"
vpn_site2_lan: "192.168.110.0/24"
vpn_site2_admin: "192.168.130.0/24"
