# Vérifie si Vault est déjà initialisé
- name: Check Vault init status
  ansible.builtin.shell: vault operator init -status
  environment:
    VAULT_ADDR: "https://{{ vault_listen_address }}:8200"
    VAULT_SKIP_VERIFY: "true"
  register: vault_init_status
  failed_when: vault_init_status.rc == 1

# Initialise Vault si pas encore fait
- name: Initialize Vault
  ansible.builtin.shell: >
    vault operator init
    -key-shares=1
    -key-threshold=1
    -format=json
  environment:
    VAULT_ADDR: "https://{{ vault_listen_address }}:8200"
    VAULT_SKIP_VERIFY: "true"
  register: vault_init_output
  when: vault_init_status.rc == 2

# Sauvegarde les clés dans un fichier sur la VM
- name: Save Vault init keys
  ansible.builtin.copy:
    content: "{{ vault_init_output.stdout }}"
    dest: /etc/vault.d/init.json
    owner: vault
    group: vault
    mode: '0600'
  when: vault_init_status.rc == 2

# Unseal Vault
- name: Unseal Vault
  ansible.builtin.shell: >
    vault operator unseal
    {{ (vault_init_output.stdout | from_json).unseal_keys_b64[0] }}
  environment:
    VAULT_ADDR: "https://{{ vault_listen_address }}:8200"
    VAULT_SKIP_VERIFY: "true"
  when: vault_init_status.rc == 2

# Active le moteur KV
- name: Enable KV secrets engine
  ansible.builtin.shell: vault secrets enable -path=secret kv-v2
  environment:
    VAULT_ADDR: "https://{{ vault_listen_address }}:8200"
    VAULT_SKIP_VERIFY: "true"
    VAULT_TOKEN: "{{ (vault_init_output.stdout | from_json).root_token }}"
  when: vault_init_status.rc == 2
  failed_when: false
