---
# Play 1 : Génère la PKI sur admin_vm Site 1 (si pas encore fait)
# et configure OpenVPN serveur sur pfSense-S1
- name: Generate PKI and configure OpenVPN server on Site 1
  import_playbook: vpn.yml

# Play 2 : Configure OpenVPN client sur pfSense-S2
- name: Configure OpenVPN client on pfSense Site 2
  hosts: firewall_s2
  gather_facts: false

  roles:
    - role: pfsense_network_s2
      tasks_from: vpn
