---
ansible_python_interpreter: /usr/local/bin/python3.11

wan_interface: vtnet0
trunk_interface: vtnet1

lan_vlan: 110
dmz_vlan: 120
admin_vlan: 130

lan_ip: 192.168.110.1
dmz_ip: 192.168.120.1
admin_ip: 192.168.130.1

bastion_ip: 192.168.120.10
webserver_ip: 192.168.110.100

# NAT ports WAN → VMs internes
bastion_nat_port: "2233"
webserver_nat_port: "2234"

# IPs externes autorisees
epitetch_network_ip: "163.5.3.84"
samy_network_ip: "90.49.150.217"
anais_network_ip: "176.159.255.103"

# VPN Site-a-Site
site1_wan_ip: "5.196.51.228"
vpn_port: 1194
vpn_tunnel_network: "10.0.0.0/30"
vpn_site1_lan: "192.168.10.0/24"
vpn_site1_admin: "192.168.30.0/24"
