- import_tasks: vlans.yml
  tags: vlans

- import_tasks: interfaces.yml
  tags: interfaces

- import_tasks: aliases.yml
  tags: [aliases, nat, rules]

- import_tasks: nat.yml
  tags: nat

- import_tasks: rules.yml
  tags: rules

- import_tasks: vpn.yml
  tags: vpn