# Règles WAN

- name: Allow HTTPS to firewall from Epitech
  pfsensible.core.pfsense_rule:
    name: "Allow HTTPS firewall 163.5.3.84"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ epitech_network_ip }}"
    destination: "(self)"
    destination_port: "443"
    state: present

- name: Allow SSH to firewall from Epitech
  pfsensible.core.pfsense_rule:
    name: "Allow SSH firewall 163.5.3.84"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ epitech_network_ip }}"
    destination: "(self)"
    destination_port: "22"
    state: present

- name: Pc Jojo to Vm1 SSH
  pfsensible.core.pfsense_rule:
    name: "Pc Jojo => Vm1"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ epitech_network_ip }}"
    destination: "{{ lan_vm_ip }}"
    destination_port: "22"
    state: present

- name: Reseau Epitech to admin_vm SSH
  pfsensible.core.pfsense_rule:
    name: "Reseau Epitech => Vm1"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ epitech_network_ip }}"
    destination: "{{ admin_vm_ip }}"
    destination_port: "22"
    state: present

- name: Chez Jaures HTTPS to firewall
  pfsensible.core.pfsense_rule:
    name: "Chez Jaures HTTPS"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ jaures_network_ip }}"
    destination: "(self)"
    destination_port: "443"
    state: present

- name: Chez Jaures SSH to firewall
  pfsensible.core.pfsense_rule:
    name: "Chez Jaures SSH firewall"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ jaures_network_ip }}"
    destination: "(self)"
    destination_port: "22"
    state: present

- name: Reseau Jaures to Vm1 SSH
  pfsensible.core.pfsense_rule:
    name: "Réseau Jaures => Vm1"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ jaures_network_ip }}"
    destination: "{{ lan_vm_ip }}"
    destination_port: "22"
    state: present

- name: Reseau Jaures to Vm2 SSH
  pfsensible.core.pfsense_rule:
    name: "Réseau Jaures => Vm2"
    action: pass
    interface: WAN
    ipprotocol: inet
    protocol: tcp
    source: "{{ jaures_network_ip }}"
    destination: "{{ admin_vm_ip }}"
    destination_port: "22"
    state: present

# Règles inter-VLAN : Admin VM => LAN VM

- name: Admin VM to LAN VM SSH
  pfsensible.core.pfsense_rule:
    name: "Admin => LAN SSH"
    action: pass
    interface: admin
    ipprotocol: inet
    protocol: tcp
    source: "{{ admin_vm_ip }}"
    destination: "{{ lan_vm_ip }}"
    destination_port: "22"
    state: present

- name: Admin VM to LAN VM OpenSearch
  pfsensible.core.pfsense_rule:
    name: "Admin => LAN OpenSearch"
    action: pass
    interface: admin
    ipprotocol: inet
    protocol: tcp
    source: "{{ admin_vm_ip }}"
    destination: "{{ lan_vm_ip }}"
    destination_port: "9200"
    state: present

- name: Admin VM to LAN VM NetBox
  pfsensible.core.pfsense_rule:
    name: "Admin => LAN NetBox"
    action: pass
    interface: admin
    ipprotocol: inet
    protocol: tcp
    source: "{{ admin_vm_ip }}"
    destination: "{{ lan_vm_ip }}"
    destination_port: "443"
    state: present
