---
- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
