# Assignation des interfaces

# LAN
- name: Configure LAN interface
  pfsensible.core.pfsense_interface:
    descr: LAN
    interface: "{{ trunk_interface }}.{{ Lan_vlan }}"
    enable: true
    ipv4_type: static
    ipv4_address: "{{ lan_ip }}"
    ipv4_prefixlen: 24

# ADMIN
- name: Configure ADMIN interface
  pfsensible.core.pfsense_interface:
    descr: ADMIN
    interface: "{{ trunk_interface }}.{{ admin_vlan }}"
    enable: true
    ipv4_type: static
    ipv4_address: "{{ admin_ip }}"
    ipv4_prefixlen: 24