---
# Play 1 : Génère la PKI sur admin_vm et la stocke dans Vault
- name: Generate PKI on admin_vm
  hosts: admin_vm
  become: true
  roles:
    - role: pki
      tags: pki

# Play 2 : Configure OpenVPN + Kill Switch sur pfSense
- name: Configure OpenVPN server on pfSense
  hosts: firewall
  tasks:
    - import_role: 
        name: pfsense_network
        tasks_from: vpn
